### ISSUE TITLE
Implement Authentication System

### ISSUE THREAD

**Issue by sahilraut05** [DocuChain-Document-Ownership-DApp/DocuChain-Backend#12]
# Implement Authentication System

### Problem Statement
The architecture for the authentication system has been finalized. The next step is to implement it in the codebase to enable secure user authentication.

---

### Proposed Solution
- Implement the authentication system as per the formulated architecture.
- Ensure the system includes:
  - User registration and login functionality.
  - Token-based authentication (e.g., JWT or OAuth2).
  - Role-based access control (if applicable).
  - Proper error handling for authentication failures.

---

### Tasks Checklist
- [x] Set up routes for authentication (e.g., `/register`, `/login`, `/logout`).
- [x] Implement user registration and login functionality.
- [x] Integrate token-based authentication for session management.
- [x] Add middleware to protect routes and enforce authentication/authorization.
- [x] Write unit and integration tests for the authentication system.
- [x] Document the implemented authentication system.

---

### Expected Benefits
- Establishes a secure and functional authentication system for the platform.
- Provides a foundation for protecting user data and restricting access to authorized users.
- Facilitates future scalability and integration of additional features.

---

### References
- [JWT Authentication Guide](https://jwt.io/introduction)
- [Express.js Middleware](https://expressjs.com/en/guide/using-middleware.html)
- [Node.js Best Practices](https://github.com/goldbergyoni/nodebestpractices)

**Comment by Krushnal121** [comment]
# Authentication API Documentation

## Overview
This authentication system implements a secure, blockchain-wallet-based authentication mechanism using nonce generation and signature verification. The system leverages Ethereum-style wallet authentication to provide a decentralized and secure way of user authentication.

## Authentication Flow

### 1. Generate Nonce Endpoint
- **Endpoint:** `http://localhost:3000/auth/generate-nonce`
- **HTTP Method:** POST
- **Purpose:** Generate a unique nonce for signature challenge

#### Request
```json
{
    "walletAddress": "0xUserWalletAddress"
}
```

#### Response
```json
{
    "nonce": "0xWalletAddress:Timestamp:RandomString"
}
```

#### Key Characteristics
- Nonce combines wallet address, timestamp, and a random string
- Prevents replay attacks
- Timestamp ensures nonce expiration
- Unique for each authentication attempt

### 2. Verify Signature Endpoint
- **Endpoint:** `http://localhost:3000/auth/verify-signature`
- **HTTP Method:** POST
- **Purpose:** Verify user's cryptographic signature and issue authentication tokens

#### Request Body
```json
{
    "walletAddress": "0xUserWalletAddress",
    "signature": "0xSignatureGeneratedByWallet",
    "nonce": "0xGeneratedNonceFromPreviousStep"
}
```

#### Response
```json
{
    "accessToken": "JWT_ACCESS_TOKEN",
    "refreshToken": "JWT_REFRESH_TOKEN"
}
```

#### Token Characteristics
- **Access Token**:
  - Short-lived (typically 1 hour)
  - Contains wallet address
  - Used for authenticating requests
  - Must be included in `Authorization` header

- **Refresh Token**:
  - Longer-lived (typically 30 days)
  - Used to obtain new access tokens
  - Prevents frequent re-authentication

### 3. Refresh Token Endpoint
- **Endpoint:** `http://localhost:3000/auth/refresh-token`
- **HTTP Method:** POST
- **Purpose:** Generate a new access token using a valid refresh token

#### Request Body
```json
{
    "refreshToken": "EXISTING_REFRESH_TOKEN"
}
```

#### Response
```json
{
    "accessToken": "NEW_JWT_ACCESS_TOKEN"
}
```

## Security Mechanisms

### Nonce Generation
1. Combines wallet address to tie nonce to specific user
2. Includes timestamp to implement expiration
3. Adds random string to prevent predictability

### Signature Verification
1. User signs nonce using wallet private key
2. Server verifies signature matches:
   - Wallet address
   - Original nonce
   - Signature cryptographic validity

### Token Management
- JWT (JSON Web Tokens) used for stateless authentication
- Tokens contain minimal claims to reduce payload size
- Short-lived access tokens minimize security window
- Refresh tokens enable seamless re-authentication

## Best Practices & Recommendations

### Client-Side
- Store tokens securely (preferably in secure storage)
- Implement token refresh logic before expiration
- Handle token invalidation gracefully

### Server-Side
- Implement token blacklisting/revocation mechanism
- Use strong, environment-specific secret keys
- Regularly rotate signing keys
- Implement proper error handling and logging

## Error Handling

### Common Error Responses
- **400 Bad Request**: Invalid input, malformed request
- **401 Unauthorized**: 
  - Invalid signature
  - Expired nonce
  - Invalid/expired tokens
- **500 Internal Server Error**: Unexpected server-side issues

## Example Authentication Workflow
1. Client requests nonce
2. User signs nonce with wallet
3. Client sends signed nonce
4. Server verifies signature
5. Server issues access and refresh tokens
6. Client uses access token for subsequent requests
7. Client refreshes token before expiration

## Logging & Monitoring
- Comprehensive logging of authentication events
- Track:
  - Authentication attempts
  - Successful/failed verifications
  - Token issuance
  - Potential security anomalies
