### ISSUE TITLE
Verify Document Ownership Before Retrieval

### ISSUE THREAD

**Issue by sahilraut05** [DocuChain-Document-Ownership-DApp/DocuChain-Backend#16]
# Verify Document Ownership Before Retrieval

### Problem Statement
The current system does not verify document ownership before allowing retrieval, potentially leading to unauthorized access to sensitive documents. Ownership validation is crucial to maintain data integrity and user trust in the platform.

---

### Proposed Solution
- Implement a middleware or service in the backend to verify document ownership before retrieval.
- Verify that the requesting user is either:
  - The owner (issuer or recipient) of the document.
  - Authorized by the owner via explicit permissions or roles.
- Deny access to users who fail ownership validation, returning an appropriate error response.

---

### Endpoint Details
- **Affected Endpoints:**  
  - `/api/documents/:docId`
  - `/api/documents/issued` (if applicable to bulk retrieval)
- **Method:** `GET`
- **Additional Security Check:** Validate ownership based on the `userId` in the authenticated token against the document's metadata.

**Example Error Response for Unauthorized Access:**
```json
{
  "success": false,
  "error": "Access denied. You do not own this document or lack proper permissions."
}
```
---
### Tasks Checklist
- [ ] Analyze existing document retrieval endpoints to identify where ownership verification is needed.
- [ ] Implement a middleware or service to verify ownership based on:
  - Authenticated user's ID.
  - Document metadata (issuer, recipient, etc.).
- [ ] Add error handling for unauthorized access attempts.
- [ ] Write unit and integration tests for ownership validation.
- [ ] Update API documentation to include ownership validation details.

---

### Expected Benefits
- Prevents unauthorized access to sensitive documents.
- Enhances security and builds user trust in the platform.
- Aligns the system with best practices for access control and data privacy.

---

### References
- [Express.js Middleware Documentation](https://expressjs.com/en/guide/using-middleware.html)
- [OWASP Access Control Guidelines](https://owasp.org/www-community/Access_Control)
