### ISSUE TITLE
Modify Ownership Transfer Endpoint to Return Only Success or Failure

### ISSUE THREAD

**Issue by sahilraut05** [DocuChain-Document-Ownership-DApp/DocuChain-Backend#21]
# Modify Ownership Transfer Endpoint to Return Only Success or Failure

### Problem Statement
The current ownership transfer endpoint provides extensive details in its response, which may not be necessary for its primary function. Simplifying the response to only indicate success or failure of the transaction will reduce payload size and improve clarity.

---

### Proposed Solution
- Update the ownership transfer endpoint to return only the following response structure:
  - **Success Response:**
    ```json
    {
      "success": true,
      "message": "Ownership transfer completed successfully."
    }
    ```
  - **Failure Response:**
    ```json
    {
      "success": false,
      "message": "Ownership transfer failed. Please try again or contact support."
    }
    ```
- Refactor the backend logic to:
  - Remove unnecessary details from the response payload.
  - Ensure that the status of the transaction is clearly communicated.
- Update tests to reflect the simplified response format.
- Communicate this change to API consumers and update documentation.

---

### Endpoint Details

**Affected Endpoint:** `/api/documents/transfer`  
**Method:** `POST`  
**Change Summary:** Modify the response to only include transaction status and message.

---

### Tasks Checklist
- [x] Review the current implementation of the `/api/documents/transfer` endpoint.
- [x] Update the response payload to include only `success` and `message` fields.
- [x] Refactor any dependent services or middleware to align with the new response format.
- [x] Write or update unit and integration tests to validate the modified response.
- [x] Update API documentation to reflect the simplified response format.
- [x] Notify API consumers about the changes and provide a transition timeline if required.

---

### Expected Benefits
- Reduces response payload size, improving performance.
- Simplifies the endpoint, making it easier to consume and integrate.
- Aligns the endpoint's functionality with its primary purpose.

---

### References
- [Express.js Response Handling](https://expressjs.com/en/api.html#res.json)
- [Best Practices for API Design](https://restfulapi.net/best-practices/)
