### ISSUE TITLE
Create an Endpoint for Enquiring All Documents Issued from a Certain User ID to a Certain User ID

### ISSUE THREAD

**Issue by sahilraut05** [DocuChain-Document-Ownership-DApp/DocuChain-Backend#5]
# Create an Endpoint for Enquiring All Documents Issued from a Certain User ID to a Certain User ID

### Problem Statement

Currently, there is no functionality to query documents issued between specific users. This limitation hinders the ability to track document ownership transfers and verify document transactions effectively.

---

### Proposed Solution

Develop a new REST API endpoint that retrieves documents issued between two specific users, providing:
- Comprehensive document transaction tracking
- Transparent ownership transfer mechanism
- Easy verification of inter-user document exchanges

---

### Endpoint Details

**Method:** `GET`  
**Endpoint:** `/api/documents/issued`  
**Query Parameters:**
- `fromUserId` (required): The ID of the user issuing the documents.
- `toUserId` (required): The ID of the user receiving the documents.

**Response Example:**
```json
{
  "success": true,
  "data": [
    {
      "docId": "12345",
      "issuer": "user001",
      "recipient": "user002",
      "timestamps": {
        "issuedAt": "2024-11-27T12:00:00Z",
        "transferredAt": "2024-11-28T15:00:00Z"
      }
    },
    {
      "docId": "67890",
      "issuer": "user001",
      "recipient": "user002",
      "timestamps": {
        "issuedAt": "2024-10-15T09:30:00Z",
        "transferredAt": "2024-10-16T10:00:00Z"
      }
    }
  ]
}
```
---

### Tasks Checklist
- [x] Define the endpoint in the backend router.
- [x] Create a service or query function to fetch the data from the database.
- [x] Validate the `fromUserId` and `toUserId` query parameters.
- [x] Ensure proper error handling for:
  - Missing or invalid user IDs.
  - No documents found for the given users.
- [x] Write unit and integration tests for the endpoint.
- [x] Update API documentation to include this endpoint.

---

### Expected Benefits
- Enables users to track document transactions between specific parties.
- Improves transparency and auditability of document ownership.

---

### References
- [Express.js Routing Documentation](https://expressjs.com/en/guide/routing.html)
- [Node.js Best Practices](https://github.com/goldbergyoni/nodebestpractices)

**Comment by Krushnal121** [comment]
# 📄 Document Search API Endpoint

## 🎯 Overview
The Document Search API provides a robust mechanism for retrieving document metadata based on issuer and recipient addresses, addressing the need for transparent document transaction tracking.

## 🚀 Endpoint Details

### Endpoint Specification
- **Method:** `POST`
- **Route:** `/api/documents/search`
- **Content-Type:** `application/json`

### Request Payload
```json
{
  "issuerAddress": "0x1234...",
  "recipientAddress": "0x5678..."
}
```

## 🔍 Request Parameters

### Issuer Address
- **Type:** Ethereum Address
- **Format:** `0x` prefixed hexadecimal string
- **Validation:** Must be a valid 40-character hex address
- **Required:** Optional (but at least one address must be provided)

### Recipient Address
- **Type:** Ethereum Address
- **Format:** `0x` prefixed hexadecimal string
- **Validation:** Must be a valid 40-character hex address
- **Required:** Optional (but at least one address must be provided)

## 📦 Response Structure

### Successful Response
```json
{
  "documents": [
    {
      "docId": "unique_document_identifier",
      "issuer": "0x_issuer_address",
      "recipient": "0x_recipient_address", 
      "createdAt": "2024-01-01T00:00:00.000Z",
      "updatedAt": "2024-01-02T00:00:00.000Z"
    }
  ],
  "totalCount": 1,
  "processingTime": 50,
  "searchCriteria": {
    "issuerAddress": "0x1234...",
    "recipientAddress": "0x5678..."
  }
}
```

## 🛡️ Validation Rules
1. At least one address (issuer or recipient) must be provided
2. Addresses must be valid Ethereum format (`0x` + 40 hex characters)
3. Empty or malformed addresses will trigger a `400 Bad Request`

## 🚨 Error Scenarios

### No Search Criteria
- **Status:** `400 Bad Request`
- **Message:** `Please provide either issuer or recipient address`

### Invalid Address Format
- **Status:** `400 Bad Request`
- **Message:** `Invalid issuer address format` or `Invalid recipient address format`

### Server Error
- **Status:** `500 Internal Server Error`
- **Response:** Includes detailed error information

## 🔒 Security Considerations
- Validates Ethereum address format
- Logs all search attempts
- Prevents potential injection or malicious queries
- Returns minimal document metadata

## 📊 Performance Metrics
- Designed for efficient querying
- Minimal payload transmission
- Rapid document metadata retrieval

## 🔗 Related Issue
**Issue #5: Create an Endpoint for Enquiring All Documents Issued from a Certain User ID to a Certain User ID**

### ✅ Implementation Status
- [x] Endpoint developed
- [x] Address validation implemented
- [x] Comprehensive logging added
- [x] Error handling established
- [x] Metadata-only response created

## 💡 Usage Examples

### Example 1: Search by Issuer
```bash
curl -X POST /api/documents/search \
     -H "Content-Type: application/json" \
     -d '{"issuerAddress": "0x1234..."}'
```

### Example 2: Search by Recipient
```bash
curl -X POST /api/documents/search \
     -H "Content-Type: application/json" \
     -d '{"recipientAddress": "0x5678..."}'
```

### Example 3: Search by Both Addresses
```bash
curl -X POST /api/documents/search \
     -H "Content-Type: application/json" \
     -d '{
         "issuerAddress": "0x1234...", 
         "recipientAddress": "0x5678..."
     }'
```

## 🔮 Future Enhancements
- Implement pagination for large result sets
- Add more granular filtering options
- Enhance performance with indexing

## 📝 Notes
- Timestamps use ISO 8601 format
- Processing time in milliseconds
- Designed for scalability and efficiency
